export const PACKAGE_CATEGORY_FIELDS = {
  "Antennas Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  BGA: [
    "Body Length",
    "Body Width",
    "Height",
    "Number of Columns",
    "Number of Rows",
    "Pin Diameter",
    "Pin Pitch",
    "Row Pitch",
  ],
  "Capacitor Al Electrolytic": [
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Span",
    "Pin Width",
  ],
  "Capacitor Chip Non-polarised": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Capacitor Chip Polarised": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Capacitor Moulded Non Polarised": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Capacitor Moulded Polarised": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Capacitor, Polarized Radial Diameter": [
    "Body Width",
    "Height",
    "Pin Pitch",
    "PTH Pin Size",
  ],
  "Capacitors, Polarized Axial Diameter Horizontal Mounting": [
    "Body Length",
    "Body Width",
    "PTH Pin Size",
  ],
  "Ceramic Dual-In-Line Packages": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Diodes Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Diodes Chip Non-polarised": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Diodes Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Diodes Moulded Non Polarised": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Diodes, Axial Diameter Horizontal Mounting": [
    "Body Length",
    "Body Width",
    "PTH Pin Size",
  ],
  "Dual-In-Line Packages": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Dual-In-Line Sockets": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Width",
    "Row Pitch",
    "Stand Off",
  ],
  "Ferrite Bead Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Fuses Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Fuses Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Header, Receptacle - Right Angle PTH Box": [
    "Body Length",
    "Body Offset X",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Receptacle - Straight PTH Box": [
    "Body Length",
    "Body Offset X",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Shrouded": [
    "Body Length",
    "Body Offset X",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Shrouded - Right Angle PTH Box": [
    "Body Length",
    "Body Offset X",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Shrouded - Straight PTH Box": [
    "Body Length",
    "Body Offset X",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Unshrouded - Right Angle PTH Pin": [
    "Body Length",
    "Body Offset Y",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Length",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Header, Unshrouded - Single Row Staggered SMD Pin": [
    "Body Height",
    "Body Length",
    "Body Width",
    "Pin Height",
    "Pin Pitch",
    "Pin Span",
    "Pin Width",
    "Stand Off",
  ],
  "Header, Unshrouded - Straight SMD Pin": [
    "Body Height",
    "Body Length",
    "Body Width",
    "Mounting Pin Diameter",
    "Mounting Pin Style",
    "Mounting Pin1 X",
    "Mounting Pin1 Y",
    "Mounting Pin2 X",
    "Mounting Pin2 Y",
    "Number of Rows",
    "Pin Length",
    "Pin Ordering",
    "Pin Pitch",
    "Pin Span",
    "Pin Width",
    "Row Pitch",
    "Stand Off",
  ],
  "Header, Vertical": [
    "Body Height",
    "Body Length",
    "Body Width",
    "Height",
    "Lead Length",
    "Number of Rows",
    "Pin Ordering",
    "Pin Pitch",
    "PTH Pin Size",
    "Row Pitch",
  ],
  "Inductor Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Inductors Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Inductors Precision Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Inductors, Axial Diameter Horizontal Mounting": [
    "Body Length",
    "Body Width",
    "PTH Pin Size",
  ],
  "LED Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "LEDs Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Plastic Leaded Chip Carrier": [
    "Body Length",
    "Body Width",
    "Height",
    "Left/Right Pins",
    "Pin Pitch",
    "Pin Span 1",
    "Pin Span 2",
    "Pin Width",
    "PLCC Pin Span 1",
    "PLCC Pin Span 2",
    "Top/Bottom Pins",
  ],
  "Quad Flat No-Lead": [
    "Body Length",
    "Body Width",
    "Height",
    "Left/Right Pins",
    "Pin Length",
    "Pin Pitch",
    "Pin Width",
    "Stand Off",
    "Thermal Pad Length",
    "Thermal Pad Width",
    "Top/Bottom Pins",
  ],
  "Quad Flat Packages": [
    "Body Length",
    "Body Width",
    "Height",
    "Left/Right Pins",
    "Pin Length",
    "Pin Pitch",
    "Pin Span 1",
    "Pin Span 2",
    "Pin Width",
    "Stand Off",
    "Thermal Pad Length",
    "Thermal Pad Width",
    "Top/Bottom Pins",
  ],
  "Resistor Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Resistor Moulded": [
    "Body Width",
    "Height",
    "Pin Length 1",
    "Pin Length 2",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Resistors, Axial Diameter Horizontal Mounting": [
    "Body Length",
    "Body Width",
    "PTH Pin Size",
  ],
  "SO Transistor Flat Lead": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Stand Off",
  ],
  "SOT223 (3-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
    "Stand Off",
  ],
  "SOT223 (4-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
    "Stand Off",
  ],
  "SOT223 (5-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
    "Stand Off",
  ],
  "SOT23 (3-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Stand Off",
  ],
  "SOT23 (5-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
    "Stand Off",
  ],
  "SOT23 (6-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Stand Off",
  ],
  "SOT23 (8-Pin)": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width 1",
    "Pin Width 2",
    "Stand Off",
  ],
  "Small Outline Diode": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Span",
    "Pin Width",
    "Stand Off",
  ],
  "Small Outline Diode Flat Lead": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Span",
    "Pin Width",
  ],
  "Small Outline No-lead": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Width",
    "Thermal Pad Length",
    "Thermal Pad Width",
  ],
  "Small Outline Packages": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Span",
    "Pin Width",
    "Stand Off",
    "Thermal Pad Length",
    "Thermal Pad Width",
  ],
  "Thermistors Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
  "Transistor Outline, Vertical": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Length",
    "Pin Pitch",
    "Pin Spacing",
    "Pin Width",
    "Stand Off",
    "Tab Protrusion",
    "Tab to Pin Centres",
  ],
  "Varistors Chip": [
    "Body Length",
    "Body Width",
    "Height",
    "Pin Width 1",
    "Pin Width 2",
  ],
} as const satisfies Record<string, readonly string[]>;

export type SourceMode = "upload" | "url";

export type PackageCategory = keyof typeof PACKAGE_CATEGORY_FIELDS;

export type ConfidenceLevel = "high" | "medium" | "low";

export type MeasurementFieldStatus = "Extracted" | "Needs review" | "Not found";

export type MeasurementFieldRow = {
  confidence?: ConfidenceLevel;
  evidencePages?: number[];
  field: string;
  status: MeasurementFieldStatus;
  value: string;
};

export type PinRow = {
  confidence?: ConfidenceLevel;
  evidencePages?: number[];
  pinName: string;
  pinNumber: string;
};

export type PackageSelection = {
  alternatives: string[];
  confidence: ConfidenceLevel;
  selectedPackage: string;
};

export type ReviewSummary = {
  needsReview: boolean;
  notes: string[];
};

export type ProviderMeta = {
  model: string;
  provider: string;
};

export type DatasheetExtractionResponse = {
  fields: MeasurementFieldRow[];
  packageCategory: PackageCategory;
  packageSelection: PackageSelection;
  partNumber: string;
  pinRows: PinRow[];
  providerMeta: ProviderMeta;
  review: ReviewSummary;
  sourceLabel: string;
  sourceMode: SourceMode;
};

export const packageCategoryEntries = Object.entries(
  PACKAGE_CATEGORY_FIELDS,
) as Array<[PackageCategory, readonly string[]]>;

export const packageCategories = packageCategoryEntries.map(
  ([packageCategory]) => packageCategory,
);
